language: node_js

node_js:
    - "12"

deploy:
  provider: script
  script: npm start
  skip_cleanup: true
  on:
    tags: false

notifications:
  email:
    recipients:
    - paulluna0215@gmail.com
    on_success: change
    on_failure: always