language: node_js
node_js:
    - "12"
services: mongodb
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: npm test
  skip_cleanup: true
  on:
    tags: false

notifications:
  email:
    recipients:
    - paulluna0215@gmail.com
    on_success: change
    on_failure: always